name: Docker Build and Publish

on:
  push:
    branches:
      - "**" # Trigger on all branches

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          # Get branch name
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

          # Get short SHA
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT

          # Sanitize branch name for Docker tag (replace / with -)
          SAFE_BRANCH=$(echo $BRANCH | sed 's/\//-/g')
          echo "safe_branch=$SAFE_BRANCH" >> $GITHUB_OUTPUT

          # Convert repository name to lowercase (ghcr requires lowercase)
          IMAGE_NAME=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

          # Build tags list
          TAGS="${IMAGE_NAME}:${SAFE_BRANCH}"
          if [ "$BRANCH" = "main" ]; then
            TAGS="$TAGS,${IMAGE_NAME}:latest"
            TAGS="$TAGS,${IMAGE_NAME}:${SHORT_SHA}"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
