name: Docker Build and Publish

on:
  push:
    branches:
      - "**" # Trigger on all branches

env:
  DOCKER_IMAGE: containerman17/frostbyte

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata
        id: meta
        run: |
          # Get branch name
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          
          # Get short SHA
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          
          # Sanitize branch name for Docker tag (replace / with -)
          SAFE_BRANCH=$(echo $BRANCH | sed 's/\//-/g')
          echo "safe_branch=$SAFE_BRANCH" >> $GITHUB_OUTPUT
          
          # Build tags list
          TAGS="${{ env.DOCKER_IMAGE }}:${SAFE_BRANCH}"
          if [ "$BRANCH" = "main" ]; then
            TAGS="$TAGS,${{ env.DOCKER_IMAGE }}:latest"
            TAGS="$TAGS,${{ env.DOCKER_IMAGE }}:${SHORT_SHA}"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
